=== Bluscream/AMPTemplates/metaconfig.schema.json
{
    "type": "array",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "",
    "minItems": 1,
    "uniqueItems": true,
    "items": {
      "type": "object",
      "required": [
        "ConfigFile",
        "AutoMap",
        "ConfigType",
        "ConfigFileTemplate"
      ],
      "properties": {
        "ConfigFile": {
          "type": "string",
          "minLength": 1
        },
        "AutoMap": {
          "type": "boolean"
        },
        "ConfigType": {
          "type": "string",
          "minLength": 1
        },
        "ConfigFileTemplate": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  }

=== Bluscream/AMPTemplates/night-of-the-deadmetaconfig.json
[
    {
        "ConfigFile":"ServerSettings.ini",
        "AutoMap":true,
        "ConfigType":"template",
        "ConfigFileTemplate":"night-of-the-dead/1420710/AMP_ServerSettings.ini"
    },
    {
        "ConfigFile":"LF/Saved/Config/ServerSettings.ini",
        "AutoMap":true,
        "ConfigType":"template",
        "ConfigFileTemplate":"night-of-the-dead/1420710/AMP_ServerSettings.ini"
    }
]
